articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp import views

app_name = 'articleapp'

urlpatterns = [
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('select_date/', TemplateView.as_view(template_name='articleapp/select_date.html'), name='select_date'),
    path('table_list/', views.table_list, name='table_list')
]

hdtsks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articleapp.urls')),
]

articleapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class CompanyRate(models.Model):
    date = models.DateField(max_length=100, blank=True, null=True)
    notice_name = models.CharField(max_length=100, blank=True, null=True)
    event = models.CharField(max_length=100, blank=True, null=True)
    basic_amount = models.CharField(max_length=100, blank=True, null=True)
    num_of_company = models.CharField(max_length=100, blank=True, null=True)
    avg_of_1365 = models.CharField(max_length=100, blank=True, null=True)
    hd_rate = models.CharField(max_length=100, blank=True, null=True)
    hd_num = models.CharField(max_length=100, blank=True, null=True)
    hj_rate = models.CharField(max_length=100, blank=True, null=True)
    hj_num = models.CharField(max_length=100, blank=True, null=True)
    hm_rate = models.CharField(max_length=100, blank=True, null=True)
    hm_num = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(max_length=100, blank=True, null=True)
    idx = models.AutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'company_rate'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

articleapp/views.py
from django.shortcuts import render
from articleapp.models import CompanyRate

# Create your views here.
# def table_list(request):
#     company_list = CompanyRate.objects.all()
#     context = {"company_list": company_list}
#     return render(request, 'articleapp/table_list.html', context)

def table_list(request):
    start = request.POST['trip-start']
    end = request.POST['trip-end']
    company_list = CompanyRate.objects.filter(date__range=[start, end])
    company_list = company_list.order_by('date')
    context = {"company_list": company_list}
    return render(request, 'articleapp/table_list.html', context)

def select_date(request):
    return render(request, 'select_date.html')

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container div {
            width: 280px;
            height: 500px;
            background-color: antiquewhite;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 1rem;
        }
        .container .item1 { height: 400px; }
        .container .item2 { height: 400px; }
        .container .item3 { height: 400px; }
        .container .item4 { height: 400px; }
        .container img, a {
            width: 100%;
            height: 100%;
            border-radius: 1rem;
            position: relative;
        }
        .img_font {
            display: block;
            text-align: center;
            width: 95%;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -65%);
            max-height: 90px;
            color: white;
            font-family: 'NanumSquareR', serif;
            filter: drop-shadow(1px 1px 5px rgb(0,0,0)) drop-shadow(1px 1px 5px rgb(0,0,0)) drop-shadow(1px 1px 5px rgb(0,0,0));
            position: absolute;
        }
    </style>

    <div class="container">
        <div class="item1">
            <a href="http://www.hdspc.co.kr/" target="_blank">
                <img src="https://picsum.photos/200/700" alt="">
                <h3 class="img_font">공식 홈페이지</h3>
            </a>
        </div>
        <div class="item2">
            <a href="{% url 'articleapp:select_date' %}">
                <img src="https://picsum.photos/200/400" alt="">
                <h3 class="img_font">사정률 분석</h3>
            </a>
        </div>
        <div class="item3">
            <img src="https://picsum.photos/200/350" alt="">
            <h3 class="img_font">머신러닝/딥러닝<br>업체별 분석</h3>
        </div>
        <div class="item4">
            <img src="https://picsum.photos/200/370" alt="">
        </div>
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

{% endblock %}

articleapp/templates/articleapp/select_date.html
{% extends 'base.html' %}


{% block content %}
    <div style="text-align: center; margin-bottom: 3rem;">
        <h3>날짜 선택</h3>
    </div>
    <script type="text/javascript">
        window.onload = function() {
        today = new Date();
        console.log("today.toISOString() >>>" + today.toISOString());
        today = today.toISOString().slice(0, 10);
        console.log("today >>>> " + today);
        day_start = document.getElementById("start");
        day_start.value = today;
        day_end = document.getElementById("end");
        day_end.value = today;
        }
    </script>

    <div style="text-align: center;">
        <form method="POST" action="{% url 'articleapp:table_list' %}" style="align-items: center">
        {% csrf_token %}
            <label for="start">시작일:</label>
            <input type="date" id="start" name="trip-start"
            min="2010-01-01" max="2025-12-31">
            &nbsp;
            &nbsp;
            <label for="start">종료일:</label>
            <input type="date" id="end" name="trip-end"
            min="2010-01-01" max="2025-12-31">
            &nbsp;
            <button type="submit" class="btn btn-primary btn-md pull-right">분석하기</button>
        </form>
    </div>

{% endblock %}

articleapp/templates/articleapp/table_list.html
{% extends 'base.html' %}
{% block content %}

    {% include 'select_date2.html' %}

    <style>
    #btn{
        border: 1px solid deepskyblue;
        background-color: rgba(0,0,0,0);
        color: deepskyblue;
        padding: 5px;
    }

    .container {
        max-width: 100%;
        height: 700px;
        overflow: auto;
    }

    .fixedHeader {
        position: sticky;
        top: 0;
        background-color: darksalmon;
    }
    tr:nth-child(even){background: #fdf5e6;}
    </style>

    <div class="container">
            <table class="table table-responsive" style="width: auto; margin-right: auto; margin-left: auto;">
                <thead style="font-size: 1.06rem; height: 50px;">
                    <tr class="fixedHeader">
                        <th width="110"><B>날짜</B></th>
                        <th width="400"><B>공고명</B></th>
                        <th width="200"><B>종목</B></th>
                        <th><B>기초금액</B></th>
                        <th><B>참여 업체 수</B></th>
                        <th><B>평균(1365)</B></th>
                        <th><B>특수 사정률</B></th>
                        <th><B>특수 예가 수</B></th>
                        <th><B>형제 사정률</B></th>
                        <th><B>형제 예가 수</B></th>
                        <th><B>휴먼 사정률</B></th>
                        <th><B>휴먼 예가 수</B></th>
                        <th width="105"><B>링크</B></th>
                    </tr>
                </thead>
                <tbody>
                {% for companyrate in company_list %}
                    <tr style="text-align: left">
                        <td>{{ companyrate.date }}</td>
                        <td>{{ companyrate.notice_name }}</td>
                        <td>{{ companyrate.event }}</td>
                        <td>{{ companyrate.basic_amount }}</td>
                        <td>{{ companyrate.num_of_company }}</td>
                        <td>{{ companyrate.avg_of_1365 }}</td>
                        <td>{{ companyrate.hd_rate }}</td>
                        <td>{{ companyrate.hd_num }}</td>
                        <td>{{ companyrate.hj_rate }}</td>
                        <td>{{ companyrate.hj_num }}</td>
                        <td>{{ companyrate.hm_rate }}</td>
                        <td>{{ companyrate.hm_num }}</td>
                        <td>
                            <button type="button" class="btn btn-outline-danger" onclick="location.href={{ companyrate.url }}" style="opacity: 1; align-items: center">
                                공고 보기
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                <tbody>
            </table>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{%  include 'head.html' %}

<body style="font-family: 'NanumSquareR';">
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
    <div class="hdtsks_footer">

        <div class="hdtsks_footer_introduction">
            <span>상호: (주)현대특수건설&nbsp; |</span> &nbsp;
            <span>대표: 김덕호&nbsp; |</span> &nbsp;
            <span>주소: 인천시 부평구 경원대로1363번길 11 602호</span><br>
            <span>사업자등록번호: 131-86-25935 &nbsp; |</span> &nbsp;
            <span>전화: 032-525-5512</span>
        </div>

        <div style="margin-top: 1rem;">
            <h6 class="hdtsks_logo">현대특수건설</h6>
        </div>

    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>현대특수건설</title>

    {# BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#  GOOGLE FONTS LINK #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet">

    {# DEFAULT CSS LINK   #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
    <div class="hdtsks_header">
        <div class="hdtsks_logo">
            <h1>현대특수건설</h1>
        </div>
        <div style="margin-top: 2rem;">
            <a href="{% url 'articleapp:list' %}" style="color: black; text-decoration: none; margin-right: 1.5rem;">
                <span>메인</span>
            </a>
            <a href="{% url 'articleapp:select_date' %}" style="color: black; text-decoration: none; margin-right: 1.5rem;">
{#            <a href="'select_date.html'" style="color: black; text-decoration: none; margin-right: 1.5rem;">#}
                <span>사정률 분석</span>
            </a>
            <a href="{% url 'articleapp:list' %}" style="color: black; text-decoration: none;">
                <span>업체별 분석</span>
            </a>
        </div>
    </div>

templates/select_date2.html
    <div style="text-align: center; margin-bottom: 3rem;">
        <h3>날짜 선택</h3>
    </div>

    <div style="margin-bottom: 3rem;">
        <script type="text/javascript">
            window.onload = function() {
            today = new Date();
            console.log("today.toISOString() >>>" + today.toISOString());
            today = today.toISOString().slice(0, 10);
            console.log("today >>>> " + today);
            day_start = document.getElementById("start");
            day_start.value = today;
            day_end = document.getElementById("end");
            day_end.value = today;
            }
        </script>

        <div style="text-align: center;">
            <form method="POST" action="{% url 'articleapp:table_list' %}" style="align-items: center">
                {% csrf_token %}
                <label for="start">시작일:</label>
                <input type="date" id="start" name="trip-start"
                min="2010-01-01" max="2035-12-31">
                &nbsp;
                &nbsp;
                <label for="start">종료일:</label>
                <input type="date" id="end" name="trip-end"
                min="2010-01-01" max="2035-12-31">
                &nbsp;
                <button type="submit" class="btn btn-primary btn-md pull-right">분석하기</button>
            </form>
        </div>
    </div>